/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOutput {
  code: string
  map?: string
}
export interface Output {
  data: string
}
/** The core of SVGO */
export function optimize(input: string): Output
